name: "Certificate Management Playbook"
version: "1.0"
tasks:
  - name: "Enroll new certificate"
    action: "enroll"
    common_name: "test.example.com"
    policy_id: "your-policy-id-here"
    key_size: 2048
    key_type: "rsa"
    output_file: "test-cert.pem"
    subject:
      country: ["US"]
      province: ["California"]
      locality: ["San Francisco"]
      organization: ["Example Corp"]
      organizational_unit: ["IT Department"]
    continue_on_error: false

  - name: "Search for certificates"
    action: "search"
    common_name: "test.example.com"
    limit: 10
    output_file: "search-results.txt"
    continue_on_error: true

  - name: "Retrieve existing certificate"
    action: "retrieve"
    certificate_id: "cert-123456"
    output_file: "retrieved-cert.pem"
    continue_on_error: true