# zcert Playbook Configuration File
# This file defines certificate management workflows with automated deployment
# Usage: zcert run --file test-run-playbook.yaml

config:
  connection:
    credentials:
      hawk-id: '165c01284c6c8d872091aed0c7cc0149'
      hawk-api: 'b97a01107585f1f037a65fafe334dcda6a42b156e1ae8df0072d203dd36f5c0c'
      platform: 'https://ztpki-dev.venafi.com/api/v2'

certificateTasks:
  - name: "WebServerCert"
    renewBefore: 30d
    request:
      csr: local
      subject:
        commonName: "www.example.com"
        country: US
        state: California
        locality: San Francisco
        organization: Example Corp
      policy: '5fe6d368-896a-4883-97eb-f87148c90896'
      sans:
        dns:
          - "example.com"
          - "api.example.com"
          - "mail.example.com"
    installations:
      - format: PEM
        file: "./certs/webserver.crt"
        chainFile: "./certs/webserver.chain.crt"
        keyFile: "./certs/webserver.key"
        backupExisting: true