name: Build

on:
  workflow_dispatch:
  push:
    branches: [ 07-03-vs-code-windows ]
  pull_request:
    branches: [ 07-03-vs-code-windows ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
            binary: "zcert"
          - goos: windows
            goarch: amd64
            binary: "zcert.exe"
          - goos: darwin
            goarch: amd64
            binary: "zcert"
          - goos: darwin
            goarch: arm64
            binary: "zcert"
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Build ${{ matrix.goos }}-${{ matrix.goarch }}
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
        CGO_ENABLED: 0
      run: |
        VERSION="1.2.0"
        GIT_COMMIT=$(git rev-parse --short HEAD)
        BUILD_TIME=$(date -u '+%Y%m%d.%H%M%S')
        GO_VERSION=$(go version | awk '{print $3}')
        LDFLAGS="-X main.Version=${VERSION} -X main.GitCommit=${GIT_COMMIT} -X main.BuildTime=${BUILD_TIME} -X main.GoVersion=${GO_VERSION}"
        go build -v -ldflags "${LDFLAGS}" -o ${{ matrix.binary }} main.go
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.binary }}-${{ matrix.goos }}-${{ matrix.goarch }}
        path: ${{ matrix.binary }}
